package com.jose.springboot.backend.mvc.models.entity;

// default package
// Generated 23 dic 2024, 12:36:30 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotEmpty;

/**
 * Flags generated by hbm2java
 */
@Entity
@Table(name = "flags")
public class Flags implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String flag;
	private Set<Jokes> jokeses = new HashSet<Jokes>(0);

	public Flags() {
	}

	public Flags(int id, String flag) {
		this.id = id;
		this.flag = flag;
	}

	public Flags(int id, String flag, Set<Jokes> jokeses) {
		this.id = id;
		this.flag = flag;
		this.jokeses = jokeses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_flags_gen")
	@SequenceGenerator(name = "seq_flags_gen", sequenceName = "seq_flags", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "flag", nullable = false)
	@NotEmpty(message = "no puede estar vacío")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "jokes_flags", joinColumns = {
			@JoinColumn(name = "flag_id", referencedColumnName="id") }, inverseJoinColumns = {
					@JoinColumn(name = "joke_id", referencedColumnName="id") })
	public Set<Jokes> getJokeses() {
		return this.jokeses;
	}

	public void setJokeses(Set<Jokes> jokeses) {
		this.jokeses = jokeses;
	}
}
