package com.jose.springboot.backend.mvc.models.entity;

// default package
// Generated 23 dic 2024, 12:36:30 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.NamedQueries;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
@NamedQueries({
    // Obtener todos los lenguajes
    @NamedQuery(
        name = "Language.todos",
        query = "SELECT l FROM Language l"
    ),
    // Buscar lenguajes por texto en el campo 'language'
    @NamedQuery(
        name = "Language.buscarPorTexto",
        query = "SELECT l FROM Language l WHERE LOWER(l.language) LIKE :searchText"
    ),
    // Buscar lenguajes sin ningún joke asociado
    @NamedQuery(
        name = "Language.lenguajesSinJokes",
        query = "SELECT l FROM Language l WHERE l.jokeses IS EMPTY"
    )
})
public class Language implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String code;
	private String language;
	private Set<Jokes> jokeses = new HashSet<Jokes>(0);

	public Language() {
	}

	public Language(int id) {
		this.id = id;
	}

	public Language(int id, String code, String language, Set<Jokes> jokeses) {
		this.id = id;
		this.code = code;
		this.language = language;
		this.jokeses = jokeses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_languages_gen")
	@SequenceGenerator(name = "seq_languages_gen", sequenceName = "seq_languages", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", length = 2)
	@Size(min = 2, max = 2, message = "El código debe tener 2 caracteres")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "language")
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<Jokes> getJokeses() {
		return this.jokeses;
	}

	public void setJokeses(Set<Jokes> jokeses) {
		this.jokeses = jokeses;
	}
}
