spring.application.name=springboot-backend-eventos
spring.datasource.url=jdbc:postgresql://localhost:5432/eventos?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.data.rest.base-path=/api
logging.level.org.hibernate.SQL=debug